### ISSUE TITLE
Добавить другие подсказки

### ISSUE THREAD

**Issue by iloveip** [vitalybaev/react-dadata#10]
Добрый день, Виталий.

Скажите, пожалуйста, планируете ли вы добавить другие справочники (организации, банки, налоговые инспекции, кем выдан паспорт и т. д.)?

**Comment by vitalybaev** [comment]
Выпущена бета версия `2.0.0-beta.0`, в ней реализован также справочник по организациям. В ближайшее время планирую реализовать все оставшиеся виды подсказок.
