### ISSUE TITLE
Как подключить подсказки по отдельным полям ФИО?

### ISSUE THREAD

**Issue by umbrellait-Said-Nurmagomedov** [vitalybaev/react-dadata#101]
Как подключить подсказки для отдельных полей ФИО ?

**Comment by satonin12** [comment]
Передай в пропс filterParts массив по чему хочешь сортировать
аля вот так
filterParts={['NAME']}
NAME - SURNAME - PATRONYMIC варианты соответсвенно

**Comment by vitalybaev** [comment]
Всё верно, @satonin12 спасибо за ответ!
