### ISSUE TITLE
При удалении данных появляется и исчезает окно с подсказками

### ISSUE THREAD

**Issue by iloveip** [vitalybaev/react-dadata#11]
При удалении данных из инпута появляется и сразу же исчезает окно с подсказками (`react-dadata__suggestions`). Скажите, пожалуйста, можно ли это как-то исправить?

Вот ссылка на [codesandbox](https://codesandbox.io/embed/react-final-from-wreact-dadata-u0skz?fontsize=14).

**Comment by vitalybaev** [comment]
Сейчас выпущена новая мажорная бета версия, можете попробовать её? Если ошибка повторяется, попрошу прислать живой пример в Codesandbox, оперативно исправлю, спасибо!

**Comment by vitalybaev** [comment]
Переоткройте ишью, если проблема будет актуальна
