### ISSUE TITLE
Ограничение области поиска адреса

### ISSUE THREAD

**Issue by legiorex** [vitalybaev/react-dadata#12]
Можно ли реализовать ограничение области поиска адреса? Например мне надо найти только адреса в Москве. В документации это поле locations.

**Comment by zazzool** [comment]
Аналогичный вопрос!

**Comment by vitalybaev** [comment]
Приветствую! У меня был период, когда я не мог уделать времени проекту и сейчас собираюсь вплотную им заняться, запланировал выход версии 2.0 с улучшенной архитектурой, включая ваше пожелание.

**Comment by vitalybaev** [comment]
Прошу прощения за долгий ответ, выпустил бета версию `2.0.0-beta.0`, в ней появилась возможность передавать для адресов:
* `filterFromBound` - `from_bound` в запросе
* `filterToBound` - `to_bound` в запросе
* `filterLocations` - `locations` в запросе
* `filterLocationsBoost` - `locations_boost` в запросе

Планирую выпустить новую версию из беты в ближайшее время

Если будут еще вопросы - спрашивайте!
