### ISSUE TITLE
Добавьте css-loader по умолчанию

### ISSUE THREAD

**Issue by Dzhakhar** [vitalybaev/react-dadata#13]
ERROR in `node_modules/react-dadata/dist/react-dadata.css 1:0`
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> .react-dadata__container {
|   position: relative;
| }

**Comment by bemulima** [comment]
дада, до сих пор не добавлен

**Comment by vitalybaev** [comment]
Сейчас выпустил бета версию `2.0.0-beta.0`, в ней по умолчанию я больше не включаю CSS файл.

По поводу самого issue - лоадер не должен находиться в моем репозитории, поскольку работа с CSS должна ложиться на плечи самого проекта: во-первых, не все используют webpack, зачем нужен в зависимостях лоадер, если на проекте Parcel или Rollup? И даже в работе с webpack в проекте может использоваться не `css-loader`, а какой-то свой.

В новом релизе как уже сказал CSS файл который идет в комплекте по умолчанию не импортируется, сделано это для того, если используется CSS-in-JS решение, в таком случае компонент принимает имена классов, которые необходимо применить.

Если будут еще вопросы - пишите, спасибо!
