### ISSUE TITLE
Установка нового значения в поле ввода

### ISSUE THREAD

**Issue by zazzool** [vitalybaev/react-dadata#15]
Подскажите, пожалуйста, как можно установить измененное значение в поле ввода компонента. Мне необходимо изменить текст строки, вместо полного адреса ("г Москва, Открытое шоссе, д 10") нужно установить только название улицы и её тип ("Открытое шоссе"). Попытка установить через пропс query безуспешна.

**Comment by vitalybaev** [comment]
Вам нужен поиск по полным адресам а в поле ввода держать только улицу? Или же вам нужен просто поиск по улицам?

**Comment by vitalybaev** [comment]
Закрываю issue, если будут вопросы - задавайте, сейчас появилось время поддерживать проект
