### ISSUE TITLE
Новые pull-requests

### ISSUE THREAD

**Issue by FrontendMetis** [vitalybaev/react-dadata#17]
Привет, я надеюсь что ты это читаешь, будь любезен примять запросы на слияния, потому-что предложенный функционал - необходим

**Comment by vitalybaev** [comment]
В виду того что выпущена бета версия полностью переписанного компонента, пулл реквесты стали неактуальны, поскольку при обновлении я постарался учесть кастомизацию.

Попрошу вас если еще актуально, попробовать `2.0.0-beta.1` и рассказать о своих впечатлениях.

Спасибо!
