### ISSUE TITLE
Добавить возможность выбора организаций из Беларуси и Казахстана

### ISSUE THREAD

**Issue by Gringer23** [vitalybaev/react-dadata#171]
в PartySuggestions нет возможности добавления организаций из Беларуси и Казахстана. Если прокинуть в url api по организациям Беларуси, то структура вывода ответа отличается от структуры организаций из России, следовательно и список формироваться не будет и из-за этого происходит ошибка на уровне библиотеки.

**Comment by vitalybaev** [comment]
@Gringer23 в версии `v2.25.0` добавлены подсказки по организациям Беларуси. Позже реализую аналогично для Казахстана.
Подсказки реализованы в отдельном компоненте `PartyBelarusSuggestions`, поскольку в DaData технически они никак не связаны с компаниями в России

**Comment by vitalybaev** [comment]
@Gringer23 в версии `v2.26.0` аналогично добавлены подсказки по организациям Казахстана
