### ISSUE TITLE
Тип DaDataSuggestion не экспортирован

### ISSUE THREAD

**Issue by PavelNen** [vitalybaev/react-dadata#24]
![image](https://user-images.githubusercontent.com/25934360/83979013-11b90680-a914-11ea-8774-7abee2d17545.png)

Тип DaDataSuggestion из примера для TypeScript не экспортирован в index.d.js

**Comment by vitalybaev** [comment]
Опубликовал обновление `2.1.1`, спасибо!
Также можно воспользоваться готовым типом `DaDataAddressSuggestion` для адреса или `DaDataPartySuggestion` для организаций.
Добавил это примечание в readme
