### ISSUE TITLE
Тип DaDataSuggestion для TypeScript не экспортирован

### ISSUE THREAD

**Issue by PavelNen** [vitalybaev/react-dadata#25]
![image](https://user-images.githubusercontent.com/25934360/83979013-11b90680-a914-11ea-8774-7abee2d17545.png)

Тип DaDataSuggestion из примера для TypeScript не экспортирован в index.d.js

**Comment by vitalybaev** [comment]
Спасибо за сообщение, исправил в `2.1.1`
Также можно воспользоваться готовым типом `DaDataAddressSuggestion` для адреса или `DaDataPartySuggestion` для организаций

**Comment by vitalybaev** [comment]
Заметил что это дублирующий #24 
Если поблема сохраняется, откройте этот issue

**Comment by PavelNen** [comment]
Да, так-то проблема легко решается, просто тип можно из другого сорсового файла подтянуть.
