### ISSUE TITLE
Добавить опцию кастомного ендпоинта подсказок

### ISSUE THREAD

**Issue by vitalybaev** [vitalybaev/react-dadata#29]

**Comment by sergeychugun** [comment]
Можно узнать когда у вас появиться данная опция? 
необходимо по клику вставлять адреса пользователей в поле ввода

[http://joxi.ru/l2ZOQPDuEJ6KjA](url)

**Comment by vitalybaev** [comment]
@sergeychugun создайте, пожалуйста новый ишшью и опишите немного подробнее, что необходимо сделать, коммуникацию будем вести там.
