### ISSUE TITLE
React 16 Support?

### ISSUE THREAD

**Issue by indapublic** [vitalybaev/react-dadata#3]
Hi, I have errors when use your component with 16 React

> ReactBaseClasses.js:64 Uncaught TypeError: this.updater.enqueueCallback is not a function

**Comment by vitalybaev** [comment]
Hi, thanks for reporting, I’ll make component working on react 16 soon👌🏻

**Comment by vitalybaev** [comment]
@indapublic I found info that it could be related to using React as dependency in `package.json` rather than peerDependency.
Could you test last release and notify me if fixes your issue?

**Comment by indapublic** [comment]
Yep, works like a charm!
