### ISSUE TITLE
Добавить опцию указания кастомного значения для поля ввода

### ISSUE THREAD

**Issue by sergeychugun** [vitalybaev/react-dadata#33]
Добрый день! Не получается поставить свое значение в поле ввода

вот на этом скрине видно как используется ваш компонент

[http://joxi.ru/ZrJl0PgUMp1E82](url)

Хочелось бы с другого компонента на странице, ставить свое значение в setaddValue(state), при клике

Ну или как то еще реализовать эту возможность.

**Comment by vitalybaev** [comment]
Опубликовал версию `2.4.0`, в ней этого можно достичь двумя способами:

1. Через пропс `value`.
В него можно передавать полный объект подсказки DaData. При его изменении в поле ввода будет помещаться значение ключа `value` подсказки DaData.

2. Через метод `setInputValue`.
Если необходимо просто поставить некое значение в поле ввода, то можно воспрользоваться методом при помощи рефа React:

```tsx
import React, { useRef } from 'react';
import { AddressSuggestions } from 'react-dadata';
import 'react-dadata/dist/react-dadata.css';

//...

const suggestionsRef = useRef<AddressSuggestions>(null);
const handleClick = () => {
  if (suggestionsRef.current) {
    suggestionsRef.current.setInputValue('Тут пример запроса');
  }
};

//...

<AddressSuggestions ref={suggestionsRef} token="API_KEY" />
<button onClick={handleClick}>Изменить поле ввода</button>
```
