### ISSUE TITLE
Ошибка при выборе клаватурными стрелками 

### ISSUE THREAD

**Issue by ZRTSKY** [vitalybaev/react-dadata#35]
Когда доходишь до конца списка стрелками и нажимаешь еще раз вниз, приложения ломается 

![Снимок экрана 2020-07-04 в 20 48 53](https://user-images.githubusercontent.com/42916643/86518160-cd982380-be37-11ea-942e-5eff2a305d3d.png)

**Comment by vitalybaev** [comment]
Прошу прощения за долгий ответ, ошибка исправлена в `2.4.2`

**Comment by ZRTSKY** [comment]
Спасибо большое
