### ISSUE TITLE
Доп функционал 

### ISSUE THREAD

**Issue by ZRTSKY** [vitalybaev/react-dadata#36]
Еще раз здравствуйте активно используем ваш сервис dadata, а именно поиск по городам, столкнулись с тем что категорически не хватает одной фичи, а именно задержка отправки запроса при вводе пользователя, и минимальное кол-во символов для отправки, я видел в issues что минимальное "кол-во символов для отправки", уже добавленно ,но не могу найти в документации описания этого метода. Мы нашли альтернативную библиотеку для решения этой задачи, вот пример ...

https://codesandbox.io/s/suspicious-worker-twz6z?file=/index.js

Но многие проекты используют именно AddressSuggestions. Если есть возможность добавить этот функционал ...
Или просто option fetchData={false}, так как мы уже написали похожий функционал , но костыльным способом через удаления токена из поля token, который работает через rxjs

![code](https://user-images.githubusercontent.com/42916643/87873783-f0e0d800-c9cc-11ea-993f-b1a2800c7713.png)

Естественно хотелось бы выпилить этот костыли, если хотя бы был бы метод option fetchData={false}

Заранее спасибо, ваш сервис супер 😌

**Comment by vitalybaev** [comment]
Еще раз здравствуйте!
Данный issue добавлен, но еще не реализован. С учетом ваших пожеланий я подниму приоритет этой задачи и постараюсь реализовать в ближайшее время.
Равно как и debounce на отправку запросов.

**Comment by ZRTSKY** [comment]
Спасибо, буду ждать ! 🙏

**Comment by vitalybaev** [comment]
1. Минимально количество символов для отправки запроса - пропс `minChars` был добавлен в одной из предыдущих версий
2. Задержка (debounce) отправки запроса добавлена пропсом `delay` только что в версии `2.6.0`

**Comment by ZRTSKY** [comment]
Спасибо большое, за отзывчивость !
