### ISSUE TITLE
Добавить событие onKeyPress/onKeyDown/onKeyUp

### ISSUE THREAD

**Issue by sergeyshaykhullin** [vitalybaev/react-dadata#37]
Хотим отлавливать нажатие Enter

Сейчас это можно сделать:
- Переопределяя `handleInputKeyPress` через ref, ломая типизацию
- Использовать event bubbling и навешивать обработчик на элемент выше

**Comment by vitalybaev** [comment]
Если нужно только отслеживать события без вмешательства в логику, то это можно сделать через inputProps. Практически все пропсы будут переданы инпуту без изменений, кроме тех, которые используются внутренне. Таких событий немного, и в них все равно вызывались события в inputProps, если они переданы. Однако это не делалось для onKeyDown и onKeyPress. В релизе `2.5.2` исправил передачу данных пропсов и отслеживать можно так:

```tsx
const handleKeyPress = (event: React.KeyboardEvent<HTMLInputElement>) => {
  //
}

const handleKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
  //
}
return (
  <AddressSuggestions
    token="DADATA_TOKEN"
    inputProps={{
      onKeyPress: handleKeyPress,
      onKeyDown: handleKeyDown,
    }}
  />
);
```
