### ISSUE TITLE
Через inputProps не пробрасывается value

### ISSUE THREAD

**Issue by sergeyshaykhullin** [vitalybaev/react-dadata#38]
### Проблема
Хотим по нажатию кнопки в инпут дадаты подставлять готовое значение

- Через `AddressSuggestions.value` подсунуть не получится, так как оно типизировано `DaDataSuggestion`
- `AddressSuggestions.defaultQuery` работает только для первого значения
- `AddressSuggestions.inputProps.value` игнорируется

```tsx
<AddressSuggestions
  ...
  value: { ??? }
  onChange={ suggestion => handleQueryChange(suggestion!.value) }
  inputProps={{
    value: query,
    onChange: e => handleQueryChange(e.currentTarget.value)
  }}/>
<button onClick={ () => handleQueryChange('Готовый пример в инпут') }>Пример</button>
```

### Потенциальные решения
- Возможно `inputProps.value` должен иметь бОльший приоритет, если задан, чем `state.query`? 
https://github.com/vitalybaev/react-dadata/blob/894a29fce43426227086ca106922587dea2f7585/src/BaseSuggestions.tsx#L276
- Либо в componentDidUpdate учитывать inputProps.value

### Воркэраунд
Через реф вызывать `setState` при вызове `handleQueryChange`

**Comment by vitalybaev** [comment]
Для ваших целей существует метод `setInputValue` классового компонента:

```tsx
import React, { useRef } from 'react';
import { AddressSuggestions } from 'react-dadata';
import 'react-dadata/dist/react-dadata.css';

//...

const suggestionsRef = useRef<AddressSuggestions>(null);
const handleClick = () => {
  if (suggestionsRef.current) {
    suggestionsRef.current.setInputValue('Тут пример запроса');
  }
};

//...

<AddressSuggestions ref={suggestionsRef} token="API_KEY" />
<button onClick={handleClick}>Изменить поле ввода</button>
```
