### ISSUE TITLE
Подсказки только названия городов

### ISSUE THREAD

**Issue by geo-spec** [vitalybaev/react-dadata#41]
Здравствуйсте. Подскажите пожалуйста, возможно ли выводить в подсказках только названия городдов, без дальнешего дополнения адреса?

**Comment by geo-spec** [comment]
Сори за офтоп, нашел предыдущий issue -
https://github.com/vitalybaev/react-dadata/issues/40

**Comment by vitalybaev** [comment]
Ничего страшного. Если нужно именно ограничить область поиска, советую посмотреть на параметры запроса, средствами DaData это работает очень хорошо

**Comment by geo-spec** [comment]
Большое спасибо за подсказку) 

Напрямую этот способ вызвал не те результаты, которые я ожидал
![image](https://user-images.githubusercontent.com/3941116/89672213-015de180-d8ed-11ea-8c57-76038b60b610.png)
![image](https://user-images.githubusercontent.com/3941116/89672440-4f72e500-d8ed-11ea-93e8-87a8721c59ef.png)


Нашел пример с офф документации - 
https://codepen.io/dadata/pen/aOxzVg?editors=1011 

`$city.suggestions({
  token: token,
  type: "ADDRESS",
  hint: false,
  geoLocation: false,
  bounds: "city-settlement",
  onSuggestionsFetch: removeNonCity
});
`
Тут используется метод onSuggestionsFetch для пост обработки и фильтрации результатов подсказок

Подскажите пожалуйста, есть ли аналогичный способ в вашем компоненте?

**Comment by vitalybaev** [comment]
В указанном примере как раз таки используется фильтрация DaData по `bounds`, в моем пакете вы можете сделать так:

```tsx
<AddressSuggestions
  token="API_KEY"
  filterFromBound="city"
  filterToBound="settlement"
/>
```

В указанном примере подсказки будут только по городам и небольшим населенным пунктам, посмотрите в документации доступные варианты. Можно дополнительно использовать renderOption, чтобы доработать отображение

**Comment by geo-spec** [comment]
Большое спасибо, Виталий =)

**Comment by geo-spec** [comment]
Извините за еще один офтоп вопрос..

Если нужна кастомная фильтрация полученных suggestions , возможно ли это реализовать через компонент?

в jQuery модуле есть метод onSuggestionsFetch который можно для это использовать.

Например тут https://codepen.io/dadata/pen/aOxzVg?editors=1011 мы фильтуруем данные по признаку 

` suggestion.data.fias_level !== "5" && suggestion.data.fias_level !== "65"`

Вопрос уже отошел от темы заголовка, мне создать отдельный issue?
