### ISSUE TITLE
Подсказки по ФИО

### ISSUE THREAD

**Issue by anaumov** [vitalybaev/react-dadata#45]
Очень не хватает!

**Comment by anaumov** [comment]
Кому горит, можно заменить ссылку в подсказках городов, будет работать)

```javascript
import { AddressSuggestions } from 'react-dadata';

class FioInput extends AddressSuggestions {
  loadSuggestionsUrl = 'https://suggestions.dadata.ru/suggestions/api/4_1/rs/suggest/fio';
}

export default FioInput;
```

**Comment by vitalybaev** [comment]
Будет сделано в течение двух дней, может даже быстрее

**Comment by vitalybaev** [comment]
Добавлен компонент `FioSuggestions` в версии `v2.8.0`.
Просьба о каких-то пожаланиях/ошибках/улучшениях открывать issue, разберемся!
