### ISSUE TITLE
Подсказки с почтовым индексом

### ISSUE THREAD

**Issue by 2700036** [vitalybaev/react-dadata#50]
Можно ли ваш компонент выдавать подсказки с индексом предлагаемого адреса? В документации не нашел

**Comment by 2700036** [comment]
Если сделать так:
renderOption={(suggestion) => suggestion.unrestricted_value  }
то пропадает выделение текста в подсказках, который пересекается с введённым в инпут.

**Comment by vitalybaev** [comment]
Здравствуйте!
Добавил в версии `2.10.0` вторым аргументом текущее значение из поля ввода.
Зная его, можно реализовать подсветку, например с помощью компонента [react-words-highlight](https://www.npmjs.com/package/react-words-highlight)
Фактически в текущем пакете используется общий пакет для поиска соответствий, в будущем подумываю выделить функцию утилиту, которую можно использовать для форматирования соответствий.
