### ISSUE TITLE
Точки после сокращений

### ISSUE THREAD

**Issue by NewbieNo9999** [vitalybaev/react-dadata#58]
Здравствуйте. На сайте dadata.ru есть способ по добавлению точек после сокращений - https://codepen.io/dadata/pen/KqMQgO?editors=1010
В вашем проекте чтоб использовать этот способ, нужно его указывать в renderOption, я так понимаю. Но в таком случае возникает ошибка TypeError: address.split is not a function. Я так понимаю, потому что то, где я использую эту функцию, не является строкой. Как решить эту проблему?

**Comment by vitalybaev** [comment]
Здравствуйте, прошу прощения за долгий ответ.
Видимо, вы использовали напрямую значение из колбека в `renderOption`.

Вот пример вашей задачи с использованием `renderOption`:

**Comment by vitalybaev** [comment]
Добавил в версии `2.10.0` вторым аргументом текущее значение из поля ввода.
Зная его, можно реализовать подсветку, например с помощью компонента [react-words-highlight](https://www.npmjs.com/package/react-words-highlight)
Фактически в текущем пакете используется общий пакет для поиска соответствий, в будущем подумываю выделить функцию утилиту, которую можно использовать для форматирования соответствий.
