### ISSUE TITLE
Искать только среди регионов или городов, без улиц?

### ISSUE THREAD

**Issue by bonzoSPb** [vitalybaev/react-dadata#7]
В оригинальной сервисе можно использовать гранулярные подсказки (bounds: city). Можно как-то допилить либу или подскажите где копать?

**Comment by vitalybaev** [comment]
В ближайшее время собираюсь реализовать данный функционал

**Comment by vitalybaev** [comment]
Добавил параметры `fromBound` и `toBound`, в соответствии с документацией могут принимать значения `'region' | 'area' | 'city' | 'settlement' | 'street' | 'house'`
