### ISSUE TITLE
Как подставить первую подсказку при потере фокуса из инпута?

### ISSUE THREAD

**Issue by Andreyneumyvannyi** [vitalybaev/react-dadata#70]
При потере фокуса из инпута нужно подставлять ближайшую подсказку

**Comment by vitalybaev** [comment]
Здравствуйте, постараюсь реализовать данный функционал в течение недели

**Comment by Andreyneumyvannyi** [comment]
Здравствуйте, буду Вам очень признателен

**Comment by vitalybaev** [comment]
В версии `v2.12.0` добавлена опция `selectOnBlur`, которая в значении `true` выбирает первую подсказку при потере фокуса

**Comment by Andreyneumyvannyi** [comment]
Спасибо огромное, очень выручили. Успехов Вам!!!

**Comment by Andreyneumyvannyi** [comment]
Здравствуйте, есть баг в подстановке значения. Если я выбрал подсказку, она не появится пока не уберу фокус
