### ISSUE TITLE
Поддержка IE 11?

### ISSUE THREAD

**Issue by OsapBender** [vitalybaev/react-dadata#72]
Планируется ли поддержка ие?

**Comment by vitalybaev** [comment]
На самом деле я даже не задумывался о такой поддержке. С другой стороны, не должно быть особых проблем поддержать его в текущих билдах.

Вы можете прислать ошибки, на которые ругается IE 11, возможно я выпущу релиз с поддержкой IE 11. Однако, эпоха IE уже заканчивается и стоит поставлять более легкий бандл для современных браузеров

**Comment by vitalybaev** [comment]
Закрываю ишью, на данный момент у меня нет возможности протестировать работу в IE 11. Если вы пришлете логи ошибок, посмотрим, что можно будет сделать
