### ISSUE TITLE
Возможно ли добавить коллбэк при вводе в поле? 

### ISSUE THREAD

**Issue by novelette17** [vitalybaev/react-dadata#74]
Сейчас onChange срабатывает только при выборе из списка найденного значения. Возможно ли добавить коллбэк onTextChange, который будет тригиться при изменении текста в поле?

**Comment by vitalybaev** [comment]
Да, вы можете определить его в пропсах инпута

```tsx

const handleChange = (event) => {
  // Ваш обработчик onChange
}

<AddressSuggestions
  inputProps={{
    onChange: handleChange,
  }}
/>
```
