### ISSUE TITLE
Ошибка SyntaxError: unterminated parenthetical

### ISSUE THREAD

**Issue by bonzoSPb** [vitalybaev/react-dadata#8]
Добрый день. 

Возникает ошибка при вводе адреса Краснодарский край, Крымский р-н, хутор Садовый + любой С/П

Например:

1) Вводим адрес Краснодарский край, Крымский р-н, хутор Садовый (Кеслеровское с/п) (можем вставить через ctrl+v, тогда ошибка сразу)

2) Нажимаем пробел или пытаемся удалить символ

3) Ошибка SyntaxError: unterminated parenthetical

С остальными адресами такой пролемы нет, подскажите в чем может быть дело?

**Comment by vitalybaev** [comment]
@bonzoSPb приношу извинения за долгий ответ. Ошибка исправлена в версии `1.2.3`
