### ISSUE TITLE
Расширения облости фильтрации

### ISSUE THREAD

**Issue by MarEeee** [vitalybaev/react-dadata#81]
В официальной доке DaData существует следующая конструкция, дабы расширить поиск до всех стран мира
`$element.suggestions({
  type: "ADDRESS",
  constraints: {
    locations: { country: "*" }
  }
});`

существует ли нечто подобное в вашем компоненте?

**Comment by vitalybaev** [comment]
Да, вы можете использовать следующие пропсы:
* `filterLocations` для `locations` в запросе
* `filterLocationsBoost` для `locations_boost` в запросе

То есть в вашем примере это будет выглядеть так:
```jsx
<AddressSuggestions
  token={API_KEY}
  filterLocations={[{ country: "*" }]}
/>
```

[Пример на CodeSandbox](https://codesandbox.io/s/react-dadata-locations-ghlfc?file=/src/App.tsx)

Обратите внимание - здесь передавать locations нужно как массив, что правильнее с точки зрения [официальной документации](https://confluence.hflabs.ru/pages/viewpage.action?pageId=1023737939).

**Comment by MarEeee** [comment]
Спасибо большое.
А как мне комбинировать несколько пропсов?
Например, в случае если я использую в своем компоненте 
`filterFromBound="city"
 filterToBound="city"`
 то возращаемые данные выглядят следующим образом 
 г Москва
 г Киров 
 г Пенза 
 поиск проводиться только по России, если же я добавляю 
` filterLocations={[{ country: "*" }]}`
 поиск начинает проводиться по всем странам, но возвращаемые данные принимают вид
` $страна, $штат/регион, $город`
хотелось бы добиться поведения как в том случае, когда отсуствует пропс 
`filterLocations={[{ country: "*" }]}`

**Comment by vitalybaev** [comment]
Точно так же и комбинируете:
```jsx
<AddressSuggestions
  token={API_KEY}
  filterFromBound="city"
  filterToBound="city"
  filterLocations={[{ country: "*" }]}
/>
```

Результатом будет как вы уже написали данные вида:
```
 $страна, $штат, $город
 $страна, $регион, $город
 $страна, $штат/регион, $город
```

То есть данные то возвращаются корректные, `filter*` оперирует сущностями: то есть какие сущности будут возвращаться в результатах. Вы указали - только города - именно они и возвращаются.
Просто по умолчанию они отображаются в такой форме и здесь уж придется передавать колбек, который на основе объекта дадаты вернет компонент ячейки, например самый простой способ:

```jsx
<AddressSuggestions
  token={API_KEY}
  filterFromBound="city"
  filterToBound="city"
  filterLocations={[{ country: "*" }]}
  renderOption={(suggestion) => {
    return suggestion.data.city;
  }}
/>
```
<img width="555" alt="CleanShot 2021-12-16 at 14 59 37@2x" src="https://user-images.githubusercontent.com/724423/146367885-de39e3e9-180b-4059-b63f-334212503bed.png">

И здесь действительно нет такой возможности чтобы после выбора опции была компактная запись. Можно будет такое добавить

Но будьте аккуратны, мир большой и если использовать короткую запись, то может случиться так, что будет сложно выбирать:

<img width="553" alt="CleanShot 2021-12-16 at 15 02 35@2x" src="https://user-images.githubusercontent.com/724423/146368220-af6522da-1515-4212-98da-8099ee98a104.png">

**Comment by MarEeee** [comment]
Виталий, огромное спасибо!
