### ISSUE TITLE
В массиве опций для компаний ключом является ИНН

### ISSUE THREAD

**Issue by Eramen** [vitalybaev/react-dadata#88]
В компоненте PartySuggestions для опций data.inn является ключом, что некорректно, так как на 1 ИНН может быть множество опций. Например, 7707083893. При выборе компании "ПАО Сбербанк", а затем изменении значения input-а, в консоль выводится предупреждения 
![image](https://user-images.githubusercontent.com/47664275/163566933-a8c3c3d1-9038-4456-9abd-803c6f4baf5f.png)

**Comment by vitalybaev** [comment]
Интересный кейс, спасибо! Выпустил фикс в `v2.19.1`
