### ISSUE TITLE
Некорректный ключ для suggestions

### ISSUE THREAD

**Issue by Eramen** [vitalybaev/react-dadata#89]
В компоненте PartySuggestions для опций data.inn с value является ключом, что некорректно, так как на один ключ может быть множество опций. Например, при вводе в input "Пупкин", выводится ошибка.
![image](https://user-images.githubusercontent.com/47664275/168022509-574899a2-6894-49bb-8cd7-0f6ce072ff25.png)
Так как имеется 2 элемента с одинаковым ИНН и value. Возможно имеет смысл переделать ключ на OGRN, так как он должен быть уникален даже для ИП.

**Comment by vitalybaev** [comment]
@Eramen спасибо за репорт! Совсем забыл, что Дадата сама предоставляет уникальный внутренний идентификатор `hid`  в организациях. Теперь точно не будет проблем

Выпустил в `v2.19.2`
