### ISSUE TITLE
Фильтр организаций по ОКВЭД

### ISSUE THREAD

**Issue by SegaMegaD** [vitalybaev/react-dadata#90]
Можно ли как-то в текущей версии компоненты отфильтровать выдачу организаций по ОКВЭД?

**Comment by vitalybaev** [comment]
На данный момент нет. Давно не смотрел за обновлениями дадаты касательно организаций, вижу, что там много всего добавили. Начал с обновления типизации организаций, думаю завтра выпущу вместе со всеми фильтрами.

**Comment by vitalybaev** [comment]
Выпущено в `v2.20.0`
