### ISSUE TITLE
Крашит приложение в ie11

### ISSUE THREAD

**Issue by Eramen** [vitalybaev/react-dadata#91]
В библиотеке используется интерфейс crypto, который отсутствует в ie11.

ReferenceError: "crypto" не определено
![image](https://user-images.githubusercontent.com/47664275/170938177-0c8e58e6-c359-48a1-9d16-b56ec78160c4.png)

Для ie11 имеет смысл добавить полифил с msCrypto.
https://developer.mozilla.org/ru/docs/Web/API/crypto_property

**Comment by vitalybaev** [comment]
Данный полифилл нужно добавлять непосредственно в приложении, где вы используете компонент.

Включение даже такого небольшого полифилла в библиотеку увеличит размер, чтобы решить проблемы < 1% пользователей.

Правда у компонента сейчас есть другая проблема в IE11 #87 однако его поддержка сейчас не является для меня приоритетной, а быстрый поиск проблемы пока ни к чему не привел.
