### ISSUE TITLE
Добавить пропс restrict_value для запроса

### ISSUE THREAD

**Issue by dzerayeah** [vitalybaev/react-dadata#92]
Возможно ли добавить пропс restrict_value, чтобы он передавался в параметры запроса? С ним можно ограничить информацию, выводимую в инпут при выборе из подсказок. Например, если было введено "ленинградский", то в подсказках будет "г Москва пр-т Ленинградский", а при выборе в инпут запишется просто "пр-т Ленинградский". [Вот тут](https://confluence.hflabs.ru/pages/viewpage.action?pageId=1023737934) есть пример

**Comment by vitalybaev** [comment]
Здравствуйте, извините за долгий ответ, в версии `v2.23.0` добавил пропс `filterRestrictValue`, в который можно передать `true`/`false`
