### ISSUE TITLE
Не изменяется состояние onChange при выборе подсказки из списка.

### ISSUE THREAD

**Issue by HeisPovedim** [vitalybaev/react-dadata#94]
У меня есть вот такой код:
```
<Controller 
      control={control}
      name="email"
      rules={{
            required: true,
            pattern: {
                  value:/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
                  message: "*Неправильный формат"
           }
      }}
      render={({ field: {onChange, onBlur, value} }) => (
            <>
                  <EmailSuggestions 
                        token={token}
                        count={5}
                        inputProps={{
                              value: value,
                              className: "inputDadata",
                              onChange: (event) => {
                                onChange(event.target.value)
                                setEmail(event.target.value)
                              },
                              onClick: (event) => onChange(event.target.value),
                              onBlur: onBlur
                        }}
                    />
            </>
      )}
/>
```
Проблема заключается в том, что когда я ввожу значение вручную, onChange меня состояние value нормально и пропускает email, но если попробовать выбрать подсказку в выпадающем списке, то onChange не сработает. Как быть?🙁

**Comment by HeisPovedim** [comment]
Если что, вот фрагмент:
```
onChange: (event) => {
  onChange(event.target.value)
  setEmail(event.target.value)
}
```

**Comment by vitalybaev** [comment]
`inputProps` - это пропсы инпута (обычного тега `<input />`), следовательно, `onChange` вызывается только когда вы печатаете в нём что-то.
Выбор подсказки от DaData вызывает `onChange`  непосредственно у компонента `<EmailSuggestions />`. Важно, что в нём в колбеке придёт объект подсказки. В вашем случае нужно ловать это событие и вытаскивать из него `value`

**Comment by HeisPovedim** [comment]
Спасибо, исправил код, оставлю тут на всякий случай:
```
<Controller 
  control={control}
  name="email"
  rules={{
    required: true,
    pattern: {
    value:/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
    message: "*Неправильный формат"
    }
  }}
  render={({ field: {onChange, onBlur, value} }) => (
  <>
    <EmailSuggestions 
        token={token}
        count={5}
        onChange={ (event) =>{
          handlerEmail(event)
          onChange(event.value)
        }}
        inputProps={{
          className: "inputDadata",
          onBlur: onBlur,
          onChange: (event) => {
            handlerEmail(event)
            onChange(event.target.value)
          }
        }}
      />
    </>
  )}
/>
```
handlerEmail:
```
const handlerEmail = (event) => {
    setEmail(event.value)
  }
```

**Comment by 7iomka** [comment]
> Спасибо, исправил код, оставлю тут на всякий случай:
> 
> ```
> <Controller 
>   control={control}
>   name="email"
>   rules={{
>     required: true,
>     pattern: {
>     value:/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
>     message: "*Неправильный формат"
>     }
>   }}
>   render={({ field: {onChange, onBlur, value} }) => (
>   <>
>     <EmailSuggestions 
>         token={token}
>         count={5}
>         onChange={ (event) =>{
>           handlerEmail(event)
>           onChange(event.value)
>         }}
>         inputProps={{
>           className: "inputDadata",
>           onBlur: onBlur,
>           onChange: (event) => {
>             handlerEmail(event)
>             onChange(event.target.value)
>           }
>         }}
>       />
>     </>
>   )}
> />
> ```
> 
> handlerEmail:
> 
> ```
> const handlerEmail = (event) => {
>     setEmail(event.value)
>   }
> ```

Спасибо дружище.
А то я ломал голову как написать адаптер.
Единственное что неприятное остается это вместо value писать defaultQuery

<img width="783" alt="image" src="https://user-images.githubusercontent.com/18473137/205134731-7f0d852d-7f29-43e4-b493-fe37879ce38c.png">
