### ISSUE TITLE
Получение ИНН и ОГРН при поиске организации

### ISSUE THREAD

**Issue by AVmillev** [vitalybaev/react-dadata#97]
Добрый день. При поиске организации хотелось бы с названием еще получать ИНН и ОГРН. Есть ли возможность как это сделать?

**Comment by vitalybaev** [comment]
В поиске организаций приходит вся информация по организациям, которая доступна для подсказок от дадаты, нужные вам поля отмечена на скриншоте.

![CleanShot 2022-09-02 at 16 31 42@2x](https://user-images.githubusercontent.com/724423/188156989-53f8ea76-2884-45cc-8abd-ef1714219aab.png)

**Comment by AVmillev** [comment]
Ну не совсем. мне нужно получить данные от выбранной организации

**Comment by vitalybaev** [comment]
Так ведь в `onChange` приходит объект подсказки, в нем вам нужен `data.inn`/`data.ogrn`

**Comment by AVmillev** [comment]
Спасибо моя невнимательность меня сгубит)
