### ISSUE TITLE
Получение ИНН и ОГРН в выбранной организации

### ISSUE THREAD

**Issue by AVmillev** [vitalybaev/react-dadata#98]
Добрый день. Извините в первом Issues #97 не совсем корректно выразился.
При выборе организации хотелось бы с названием еще получать ИНН и ОГРН в переменную или куда нить в элемент.
Есть ли возможность, как это сделать?

**Comment by vitalybaev** [comment]
Я вам ответил в #97, что в событии `onChange` вы получаете полный объект подсказки - то, что вам нужно
Для дальнейшей переписки используйте #97
